### ISSUE TITLE
Ships not moving and console spam

### ISSUE THREAD

**Issue by Dragonbreath135** [msummers123/Movecraft-3#282]
I've tried about 5 different versions of WE and WG but cannot get them to work with movecraft 5.0. I'm running a server on 1.7.2. Thanks in advance
 [Movecraft] Task #28 for Movecraft v5.0.0 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/World
        at net.countercraft.movecraft.async.AsyncManager.run(AsyncManager.java:1525) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:614) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:562) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:469) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[spigot-1.7.2-R0.4-SNAPSHOT-1339(1).jar:git-Spigot-1339]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
