### ISSUE TITLE
Movecraft 1.10.2 Did i mess something up?

### ISSUE THREAD

**Issue by stlsf4003** [msummers123/Movecraft-3#267]
So i though i would set up a little Movecraft server for me and my buds to screw around with.

I got a spigot 1.10.2 server up and running but when i went to add Movecraft it's self i got this error.

 [10:55:12] [Server thread/ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:388) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:747) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 17 more
[10:55:12] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:55:12] [Server thread/INFO]: CONSOLE: [0;32;1mReload complete.[m

did i fuck up some where during setup?

**Comment by pistols12** [comment]
I personally had troubles with the newer versions, I'm not sure if it's
just me but I honestly had to version 5. Or the 1 even before that.

I would try older versions of the movecraft to jar first.

**Comment by stlsf4003** [comment]
Is there an older version of 1.10 or am i gonna need to bump it down to 1.9?

If so, could you point me to where i could find the permissonsEx.jar for 1.10 or 1.9?

**Comment by pistols12** [comment]
I mean like, you will need to use a different movecraft jar. An older one.

**Comment by pistols12** [comment]
The reason I say this is because I have a spigot 1.9 server. It is used the
same movecraft jar for like 6 months maybe a year, at any rate I just
recently tried to upgrade to the version 5.0 or the version 6.0 and it was
getting the error you saw there.

**Comment by pistols12** [comment]
I reverted back to my older movecraft- Char and had zero issues

**Comment by pistols12** [comment]
Go on Google, search spigot movecraft, find version history, find and test
different versions.

**Comment by stlsf4003** [comment]
Right, i just found the version history of movecraft.

The older versions include.
5.0.2
5.0.1
and 
5.0

Which version do you recommend and will all three of these versions work with spigot 1.9?

**Comment by oh-noey** [comment]
Somewhere down the line the worldguard sofft dependency in movecraft broke. You just need to install worldguard and it will work fine

**Comment by pistols12** [comment]
Hm, when I had the newest world guard, newest world edit, I had this same
error above, with known good files (config and type)

Add me on Skype: tango1one

I'll send you working known good files for 1.9

**Comment by stlsf4003** [comment]
Hold that thought.

I think i might have got it working, i'll let you know after i get off work tomorrow.

**Comment by stlsf4003** [comment]
Right, sorry for the late reply but i am happy to inform you all that Movecraft now works just fine.

Thanks for all the help! :+1:

**Comment by oh-noey** [comment]
Just for record keeping's sake, could you say what was wrong

**Comment by stlsf4003** [comment]
Gladly

When i was first setting up movecraft, I was getting this error message in the server console.

[10:55:12] [Server thread/ERROR]: Error occurred while enabling Movecraft v6.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:388) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:747) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot.jar:git-Spigot-de459a2-51263e9]
at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-de459a2-51263e9]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-de459a2-51263e9]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-de459a2-51263e9]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-de459a2-51263e9]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
... 17 more
[10:55:12] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:55:12] [Server thread/INFO]: CONSOLE: �[0;32;1mReload complete.�[m

As i would later find out, i needed Worldedit and Worldguard to make it work.
Once i had those two pulgins it was smooth sailing.
